// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK-FkzK-vXQuY8bU0Gj-jwXZaaw9DEvNE',
    appId: '1:85541941443:web:df2af785ef522d4a987276',
    messagingSenderId: '85541941443',
    projectId: 'to-do-app-96381',
    authDomain: 'to-do-app-96381.firebaseapp.com',
    storageBucket: 'to-do-app-96381.appspot.com',
    measurementId: 'G-K0XH03SKVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGixUaDB6Noa2pFcQ1o0qpKQfHZ5UWrtE',
    appId: '1:85541941443:android:848ef9cc00ca8a9d987276',
    messagingSenderId: '85541941443',
    projectId: 'to-do-app-96381',
    storageBucket: 'to-do-app-96381.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrx3DI7XmViGChc47lzxW7YvTtXx1Qr0',
    appId: '1:85541941443:ios:91bbd637cf8a5ab9987276',
    messagingSenderId: '85541941443',
    projectId: 'to-do-app-96381',
    storageBucket: 'to-do-app-96381.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBrx3DI7XmViGChc47lzxW7YvTtXx1Qr0',
    appId: '1:85541941443:ios:91bbd637cf8a5ab9987276',
    messagingSenderId: '85541941443',
    projectId: 'to-do-app-96381',
    storageBucket: 'to-do-app-96381.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK-FkzK-vXQuY8bU0Gj-jwXZaaw9DEvNE',
    appId: '1:85541941443:web:68aad86132d0dec6987276',
    messagingSenderId: '85541941443',
    projectId: 'to-do-app-96381',
    authDomain: 'to-do-app-96381.firebaseapp.com',
    storageBucket: 'to-do-app-96381.appspot.com',
    measurementId: 'G-NTTRGNHZ5L',
  );

}